---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../../roles
  hosts: all
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  enable_yum_epel: true
#  name: chef_solo

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: centos/8
  - name: centos/7

suites:
  - name: default
    run_list:
    attributes:
  - name: default-nginx-full
    run_list:
    attributes:
    includes:
      - ubuntu-18.04
