---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_chef_omnibus: false
  require_ansible_omnibus: true
  enable_yum_epel: true
  ansible_connection: ssh
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: debian-buster
  - name: centos-8
  - name: centos-7
## httpd/centos7/capability issue on lxc
## https://github.com/lxc/lxd/issues/1245	= only choice is privileged
## https://bugzilla.redhat.com/show_bug.cgi?id=1012952
    driver:
      config:
        security.privileged: true
#  - name: alpine-3.4


suites:
  - name: default
    run_list:
    attributes:
  - name: default-nginx-full
    run_list:
    attributes:
    includes:
      - ubuntu-20.04
      - ubuntu-18.04
      - debian-buster
  - name: default-vascan
    run_list:
    attributes:
