---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
## FIXME! ansible 2.2.2.0? ERROR! Unexpected Exception: 'Host' object has no attribute 'remove_group'
#  ansible_version: 2.2.1.0
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  enable_yum_epel: true

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
#  - name: ubuntu-12.04
  - name: centos-7
## httpd/centos7/capability issue on lxc
## https://github.com/lxc/lxd/issues/1245	= only choice is privileged
## https://bugzilla.redhat.com/show_bug.cgi?id=1012952
    driver:
      config:
        security.privileged: true
## centos6 default still is 2.1.x
## + workaround Ansible 2.2+/cryptography: https://github.com/ansible/ansible/issues/276
## ~ need to disable call to letsencrypt module: nginx-security.yml 46,64s/^/#/
#  - name: centos-6
#    provisioner:
## Desired version, only affects apt-get installs
#      ansible_version: 2.1.2.0		## NOK
#      ansible_version: 2.1.2.0-1	## NOK
#      ansible_version: 2.1.2.0-1.el6	## NOK
#  - name: alpine-3.4


suites:
  - name: default
    run_list:
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
      - centos-7
      - centos-6
  - name: default-nginx-full
    run_list:
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
  - name: default-vascan
    run_list:
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
      - centos-7
      - centos-6
