---

- name: Update ssl path for stepca
  ansible.builtin.set_fact:
    ssl_privatedir: "/etc/ssl/private"
    ssl_dir: "/etc/ssl/certs"
    ssl_privkey: "/etc/ssl/private/{{ ansible_fqdn }}.key"
    ssl_crt: "/etc/ssl/certs/{{ ansible_fqdn }}.crt"
    ssl_fullchain: "/etc/ssl/certs/{{ ansible_fqdn }}.crt"

- name: Debian | Install small step
  when:
    - ansible_os_family == 'Debian'
  block:
    - name: Debian | Set fact
      ansible.builtin.set_fact:
        step_pkg: https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_amd64.deb
    - name: Debian | Download package
      ansible.builtin.get_url:
        url: "{{ step_pkg }}"
        dest: "{{ tmp_ssl_dir }}/{{ step_pkg | basename }}"
        mode: '0600'
        owner: root
    - name: Install small step
      ansible.builtin.package:
        deb: "{{ tmp_ssl_dir }}/{{ step_pkg | basename }}"
        state: present

- name: RedHat | Install small step
  when:
    - ansible_os_family == 'RedHat'
  block:
    - name: RedHat | Set fact
      ansible.builtin.set_fact:
        step_pkg: https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_amd64.rpm
    - name: Install small step
      ansible.builtin.package:
        name: "{{ tmp_ssl_dir }}/{{ step_pkg | basename }}"
        state: present

- name: Create new certificate for requested domain with step-ca
  ansible.builtin.command:
    # cmd: "strace step ca certificate --password-file={{ stepca_pass_file }} {{ stepca_args }} {{ ansible_fqdn }} {{ ansible_fqdn }}.crt {{ ansible_fqdn }}.key 2>/tmp/step-ca-certificate.strace"
    cmd: "step ca certificate --password-file={{ stepca_pass_file }} {{ stepca_args }} {{ ansible_fqdn }} {{ ansible_fqdn }}.crt {{ ansible_fqdn }}.key"
  args:
    chdir: /root
    creates: "/root/{{ ansible_fqdn }}.crt"

- name: Copy certificate files to needed locations
  ansible.builtin.copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    mode: "{{ item.m }}"
    remote_src: true
  loop:
    - { s: "/root/{{ ansible_fqdn }}.crt", d: "{{ hardenwebserver_ssl_cert | default(ssl_dir + '/' + ansible_fqdn + '.crt') }}", m: '0644' }
    - { s: "/root/{{ ansible_fqdn }}.key", d: "{{ hardenwebserver_ssl_key | default(ssl_privatedir + '/' + ansible_fqdn + '.key') }}", m: '0600' }
