---

- name: Update ssl path for stepca
  ansible.builtin.set_fact:
    ssl_privatedir: "/etc/ssl/private"
    ssl_dir: "/etc/ssl/certs"
    ssl_privkey: "/etc/ssl/private/{{ ansible_fqdn }}.key"
    ssl_crt: "/etc/ssl/certs/{{ ansible_fqdn }}.crt"
    ssl_fullchain: "/etc/ssl/certs/{{ ansible_fqdn }}.crt"

- name: Debian | Install small step
  when:
    - ansible_os_family == 'Debian'
  block:
    - name: Debian | Set fact
      ansible.builtin.set_fact:
        step_pkg: https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_amd64.deb
    - name: Debian | Download package
      ansible.builtin.get_url:
        url: "{{ step_pkg }}"
        dest: "{{ tmp_ssl_dir }}/{{ step_pkg | basename }}"
        mode: '0600'
        owner: root
    - name: Install small step
      ansible.builtin.package:
        deb: "{{ tmp_ssl_dir }}/{{ step_pkg | basename }}"
        state: present

- name: RedHat | Install small step
  when:
    - ansible_os_family == 'RedHat'
  block:
    - name: RedHat | Set fact
      ansible.builtin.set_fact:
        step_pkg: https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_amd64.rpm
    - name: Install small step
      ansible.builtin.package:
        name: "{{ tmp_ssl_dir }}/{{ step_pkg | basename }}"
        state: present

- name: Step-ca token
  when:
    - hardenwebserver_stepca_host is defined
    - hardenwebserver_stepca_host | length > 0
  block:
    - name: Create token on step-ca certificate server
      ansible.builtin.command:  # noqa no-changed-when
        cmd: "step ca token --provisioner-password-file={{ stepca_host_provisioner_passfile }} {{ stepca_args }} {{ ansible_fqdn }}{% if hardenwebserver_target_host_san %}{% for item in hardenwebserver_target_host_san %} --san {{ item }}{% endfor %}{% endif %}"
      delegate_to: "{{ hardenwebserver_stepca_host }}"
      register: stepca_token
    - name: Create new certificate for requested domain with step-ca and token
      ansible.builtin.command:
        cmd: "step ca certificate --token={{ stepca_token.stdout }} {{ stepca_args }} {{ ansible_fqdn }} {{ ansible_fqdn }}.crt {{ ansible_fqdn }}.key"
        # cmd: "step ca certificate --token={{ stepca_token.stdout }} {{ stepca_args }} {{ ansible_fqdn }} {{ ansible_fqdn }}.crt {{ ansible_fqdn }}.key --force"
      args:
        chdir: /root
        # if want to renew certificate, skip on file existence and add '--force' above (else overwrite question)
        creates: "/root/{{ ansible_fqdn }}.crt"

- name: Step-ca provisioner password file
  when: >
    hardenwebserver_stepca_host is not defined or
    hardenwebserver_stepca_host | length == 0
  block:
    - name: Create new certificate for requested domain with step-ca
      ansible.builtin.command:
        # cmd: "strace step ca certificate --password-file={{ stepca_pass_file }} {{ stepca_args }} {{ ansible_fqdn }} {{ ansible_fqdn }}.crt {{ ansible_fqdn }}.key 2>/tmp/step-ca-certificate.strace"
        cmd: "step ca certificate --password-file={{ stepca_pass_file }} {{ stepca_args }} {{ ansible_fqdn }} {{ ansible_fqdn }}.crt {{ ansible_fqdn }}.key"
        # this returns "Please enter the password to decrypt the provisioner key:" and blocks
        # cmd: "step ca certificate {{ stepca_args }} {{ ansible_fqdn }} {{ ansible_fqdn }}.crt {{ ansible_fqdn }}.key"
      args:
        chdir: /root
        # if want to renew certificate, can't skip on file existence
        creates: "/root/{{ ansible_fqdn }}.crt"

- name: Copy certificate files to needed locations
  ansible.builtin.copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    mode: "{{ item.m }}"
    remote_src: true
  loop:
    - { s: "/root/{{ ansible_fqdn }}.crt", d: "{{ hardenwebserver_ssl_cert | default(ssl_fullchain) }}", m: '0644' }
    - { s: "/root/{{ ansible_fqdn }}.key", d: "{{ hardenwebserver_ssl_key | default(ssl_privkey) }}", m: '0600' }
  notify:
    - Restart nginx

- name: Import certificate-stepca-autorenewal
  ansible.builtin.import_tasks: certificate-stepca-autorenewal.yml
