---
# install a basic csp report log file, consider alternatives if production

- name: Ensure csp directories exist
  ansible.builtin.file:
    dest: "{{ item.d }}"
    state: directory
    owner: "{{ item.o }}"
    mode: "{{ item.m }}"
  with_items:
    - { d: "{{ _hardenwebserver_rootdir }}/csp", o: root, m: '0755' }
    - { d: "{{ _hardenwebserver_rootdir }}/csp/log", o: "{{ www_user }}", m: '0755' }

- name: Configure csp-report script
  ansible.builtin.template:
    src: "{{ harden_nginx_cspreport_template }}"
    dest: "{{ _hardenwebserver_rootdir }}/csp/report.php"
    mode: '0644'
    backup: true

- name: Add csp test file
  ansible.builtin.copy:
    src: test-csp.html
    dest: "{{ _hardenwebserver_rootdir }}/csp/test-csp.html"
    mode: '0644'

- name: Ensure php is present
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ harden_nginx_php }}"
  register: pkg_result
  until: pkg_result is success

- name: Ensure logrotate package is present
  ansible.builtin.package:
    name: logrotate
    state: present

- name: Add csp log in logrotate
  ansible.builtin.template:
    src: logrotate-nginx.j2
    dest: /etc/logrotate.d/nginx
    mode: '0644'
    owner: root
    group: root
    validate: 'logrotate -d %s'
