---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for Debian.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Debian'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- import_tasks: local-etc-hosts-kitchen-lxd.yml

- import_tasks: travis.yml

- import_tasks: nginx.yml

- import_tasks: slow.yml

- import_tasks: php.yml
  when: harden_nginx_php_enable

- import_tasks: aide-hids.yml
- import_tasks: security-txt.yml

- import_tasks: reporting.yml
  when: hardennginx_reporting

- import_tasks: testing.yml
  when: harden_nginx_testing|bool
