---

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for Debian.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Debian'
- name: Include version-specific variables for RedHat
  ansible.builtin.include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- name: Import local-etc-hosts-kitchen-lxd
  ansible.builtin.import_tasks: local-etc-hosts-kitchen-lxd.yml

- name: Import facts
  ansible.builtin.import_tasks: facts.yml

- name: Import nginx
  ansible.builtin.import_tasks: nginx.yml

- name: Import slow
  ansible.builtin.import_tasks: slow.yml

- name: Import php
  ansible.builtin.import_tasks: php.yml
  when: harden_nginx_php_enable

- name: Import aide-hids
  ansible.builtin.import_tasks: aide-hids.yml
- name: Import security-txt
  ansible.builtin.import_tasks: security-txt.yml

- name: Import reporting
  ansible.builtin.import_tasks: reporting.yml
  when: hardennginx_reporting

- name: Import testing
  ansible.builtin.import_tasks: testing.yml
  when: harden_nginx_testing|bool
