---

- name: Naxsi not available
  ansible.builtin.fail: msg="nginx-naxsi package not available on target distribution"
  when: >
    hardenwebserver_nginx_debian_pkg is defined and
    hardenwebserver_nginx_debian_pkg == 'nginx-naxsi' and
    not (
          (ansible_distribution == 'Debian' and ansible_distribution_release == "wheezy") or
          (ansible_distribution == 'Ubuntu' and
            (ansible_distribution_release == 'precise' or ansible_distribution_release == 'trusty')
          )
        )

- name: apt | update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
  register: pkg_result
  until: pkg_result is success

- name: nginx packages install
  ansible.builtin.package: name={{ item }} state=present
  with_items: "{{ hardenwebserver_packages }}"

- import_tasks: nginx-security.yml

- import_tasks: csp-report.yml
  when: harden_nginx_cspreport_template is defined and harden_nginx_cspreport_template|string

- import_tasks: systemd.yml
  when: hardenwebserver_nginx_systemd_hardening

- block:
    - name: Centos7 | systemd reload - workaround
      ansible.builtin.command: systemctl daemon-reload  # noqa no-changed-when command-instead-of-module
    - name: Centos7 | restart nginx 1
      ansible.builtin.command: systemctl restart nginx  # noqa no-changed-when command-instead-of-module
      failed_when: false
    - name: Centos7 | restart nginx 2
      ansible.builtin.command: systemctl restart nginx  # noqa no-changed-when command-instead-of-module
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: ensure nginx is enabled and started
  ansible.builtin.service: name={{ apache_svc }} state=started enabled=yes
