---

- name: Naxsi not available
  fail: msg="nginx-naxsi package not available on target distribution"
  when: >
    hardenwebserver_nginx_debian_pkg is defined and
    hardenwebserver_nginx_debian_pkg == 'nginx-naxsi' and
    not (
          (ansible_distribution == 'Debian' and ansible_distribution_release == "wheezy") or
          (ansible_distribution == 'Ubuntu' and
            (ansible_distribution_release == 'precise' or ansible_distribution_release == 'trusty')
          )
        )

- name: nginx packages install
  package: name={{ item }} state=present
  with_items: "{{ hardenwebserver_packages }}"

- include: nginx-security.yml

- include: csp-report.yml
  when: harden_nginx_cspreport_template is defined and harden_nginx_cspreport_template|string

- include: systemd.yml
  when: hardenwebserver_nginx_systemd_hardening

- block:
    - name: Centos7 | systemd reload - workaround
      command: systemctl daemon-reload  # noqa 303
    - name: Centos7 | restart nginx 1
      command: systemctl restart nginx  # noqa 303
      failed_when: false
    - name: Centos7 | restart nginx 2
      command: systemctl restart nginx  # noqa 303
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'

- name: Flush handlers
  meta: flush_handlers

- name: ensure nginx is enabled and started
  service: name={{ apache_svc }} state=started enabled=yes
