---

- fail: msg="nginx-naxsi package not available on target distribution"
  when: hardenwebserver_nginx_debian_pkg is defined and hardenwebserver_nginx_debian_pkg == 'nginx-naxsi' and not ((ansible_distribution == 'Debian' and ansible_distribution_release == "wheezy") or (ansible_distribution == 'Ubuntu' and (ansible_distribution_release == 'precise' or ansible_distribution_release == 'trusty')))

- name: nginx packages install
  package: name={{item}} state=present
  with_items: "{{ hardenwebserver_packages }}"

- include: nginx-security.yml

- name: ensure nginx is enabled and started
  service: name={{ apache_svc }} state=started enabled=yes
