---

- name: Ensure /usr/local/scripts exists
  file:
    dest: /usr/local/scripts
    state: directory
    mode: '0755'

- name: Ensure reporting script exists
  template:
    src: "{{ hardennginx_reporting_template }}.j2"
    dest: "/usr/local/scripts/{{ hardennginx_reporting_template | basename }}"
    mode: '0755'

- name: Add nginx report in logrotate
  lineinfile:  # noqa no-tabs
    dest: /etc/logrotate.d/nginx
    line: "\t\ttest ! -x /usr/local/scripts/{{ hardennginx_reporting_template | basename }} || sudo -u syslog /usr/local/scripts/{{ hardennginx_reporting_template | basename }} 2>&1 | sudo -u syslog tee {{ hardennginx_reporting_dest }}/nginx-report-$(date +%Y%m%d) >/dev/null"
    insertafter: '^\tprerotate$'
    mode: '0644'
