---

- name: Ensure /usr/local/scripts exists
  ansible.builtin.file:
    dest: /usr/local/scripts
    state: directory
    mode: '0755'

- name: Ensure reporting script exists
  ansible.builtin.template:
    src: "{{ hardennginx_reporting_template }}.j2"
    dest: "/usr/local/scripts/{{ hardennginx_reporting_template | basename }}"
    mode: '0755'

- name: Ensure right permissions for logs dir
  ansible.builtin.file:
    dest: /var/log/nginx
    state: directory
    mode: '0755'
    owner: root
    group: "{{ harden_nginx_syslog_dir_group | default(varlog_group) }}"
