---

# initial draft (https://github.com/EdOverflow/security-txt) was placing file as /.well-known/security.txt
# ietf draf (https://www.ietf.org/id/draft-foudil-securitytxt-00.txt) says located in the website's top-level directory
- name: Ensure security.txt is present - draft-foudil-securitytxt-00
  ansible.builtin.template:
    src: "{{ harden_nginx_securitytxt_template }}"
    dest: "{{ hardenwebserver_rootdir | default(_hardenwebserver_rootdir) }}/security.txt"
    mode: '0644'
    backup: yes
  when:
    - harden_nginx_securitytxt_template is defined
    - harden_nginx_securitytxt_template | length > 0
