---

- name: Ensure override folder exists
  ansible.builtin.file:
    dest: /etc/systemd/system/nginx.service.d
    state: directory
    mode: '0755'

# if issue, check /var/log/audit/audit.log
- name: Review nginx systemd options
  ansible.builtin.template:
    src: systemd-override.conf.j2
    dest: /etc/systemd/system/nginx.service.d/override.conf
    mode: '0644'
  notify:
    - Reload systemd
    - Restart nginx

- name: Remove user/group in nginx.conf as in systemd
  ansible.builtin.replace:
    dest: /etc/nginx/nginx.conf
    regexp: '^user (.*);'
    replace: '#user \1;'
    mode: '0640'

- name: Align pid path in nginx.conf
  ansible.builtin.replace:
    dest: /etc/nginx/nginx.conf
    regexp: '^pid .*'
    replace: 'pid /run/nginx/nginx.pid;'
    mode: '0640'

- name: Ensure /run/nginx exists
  ansible.builtin.file:
    path: /run/nginx
    state: directory
    mode: '0755'
    owner: "{% if ansible_os_family == 'RedHat' %}nginx{% else %}www-data{% endif %}"

- name: Ensure directories exists
  ansible.builtin.file:
    path: "{{ item.p }}"
    mode: "{{ item.m }}"
    state: directory
  with_items: "{{ hardenwebserver_systemd_dir_acl }}"

- name: Ensure directories are accessible to www-data
  acl:
    path: "{{ item.p }}"
    entity: "{{ www_user }}"
    etype: user
    permissions: "{{ item.perm }}"
    state: present
  with_items: "{{ hardenwebserver_systemd_dir_acl }}"

- name: Ensure certificates and log files are accessible to www-data
  acl:
    path: "{{ item.p }}"
    entity: "{{ www_user }}"
    etype: user
    permissions: "{{ item.perm }}"
    state: present
  with_items: "{{ hardenwebserver_systemd_files_acl }}"

- name: Systemd
  block:
    - name: Ensure no conflicting pid path
      ansible.builtin.replace:
        dest: /lib/systemd/system/nginx.service
        regexp: "{{ item.re }}"
        replace: "{{ item.rep }}"
        mode: '0644'
      with_items:
        - { re: '^PIDFile=/run/nginx.pid', rep: '#PIDFile=/run/nginx.pid' }
        - { re: '--pidfile /run/nginx.pid', rep: '--pidfile /run/nginx/nginx.pid' }
        # Centos 7
        - { re: '^ExecStartPre=/usr/bin/rm -f /run/nginx.pid', rep: 'ExecStartPre=/usr/bin/rm -f /run/nginx/nginx.pid' }
      notify:
        - Reload systemd
        - Restart nginx
      register: nginx_systemd
  rescue:
    - import_tasks: immutable.yml
      vars:
        target_dir: /lib/systemd/system
        state: pre
    - import_tasks: immutable.yml
      vars:
        target_dir: /lib/systemd/system/nginx.service
        state: pre
    - name: Ensure no conflicting pid path (immutable)
      ansible.builtin.replace:
        dest: /lib/systemd/system/nginx.service
        regexp: '^PIDFile=/run/nginx.pid'
        replace: '#PIDFile=/run/nginx.pid'
        mode: '0644'
      notify:
        - Reload systemd
        - Restart nginx
    - import_tasks: immutable.yml
      vars:
        target_dir: /lib/systemd/system
        state: post
    - import_tasks: immutable.yml
      vars:
        target_dir: /lib/systemd/system/nginx.service
        state: post
