FROM debian:buster
RUN apt-get update

# Install Ansible
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common git systemd
RUN apt-get update
RUN apt-get install -y python sudo python-pip python-dev libffi-dev
RUN pip install ansible

# Install Ansible inventory file
RUN mkdir /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
RUN echo "[defaults]\ncallback_whitelist = profile_tasks, timer" > /etc/ansible/ansible.cfg
