---
name: default-bare

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:  # run weekly, every Tuesday 03:00
    - cron: '0 3 * * 2'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - os: ubuntu-24.04
            experimental: false
            suite: default
          - os: ubuntu-22.04
            experimental: false
            suite: default
          - os: ubuntu-20.04
            experimental: false
            suite: default
          - os: ubuntu-24.04
            experimental: false
            suite: default-multisites
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.harden_nginx
      ANSIBLE_SUITE: ${{ matrix.suite }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.ANSIBLE_ROLE }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: ACL
        run: |
          sudo apt-get install -y acl || true
          mount
          sudo mount -o remount,acl / || true
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ansible --version
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          set -x
          pwd
          env
          find -ls
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/$ANSIBLE_SUITE/default.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/$ANSIBLE_SUITE/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
      - name: On failure
        run: |
          systemctl -l --no-pager status
          systemctl -l --no-pager --failed
          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
          pip freeze
          pip3 freeze
          ip addr
          cat /etc/resolv.conf
          host www.google.com
          ping -c 1 www.google.com || true
          ping -c 1 8.8.8.8 || true
          ps axuw
          netstat -anp
        if: ${{ failure() }}
        continue-on-error: true
      - name: After script - ansible setup
        run: |
          ansible -i inventory --connection=local -m setup localhost
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - systemd
        run: |
          systemctl -l --no-pager status nginx || true
          systemctl -l --no-pager status php-fpm || true
          systemctl -l --no-pager status php7.2-fpm || true
          systemctl -l --no-pager status php7.4-fpm || true
          systemctl -l --no-pager --failed || true
          systemd-analyze --no-pager security || true
          rsyslogd -v
          nginx -V
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - etc
        run: |
          sudo cat /etc/nginx/nginx.conf
          sudo find /etc/nginx/sites-available/ -type f -exec cat {} \;
          sudo find /etc/nginx/conf.d/ -iname 'harden-nginx-*' -type f -exec cat {} \;
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - files
        run: |
          sudo find /etc/nginx -type f -ls
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - curl
        run: |
          curl -vk https://localhost
          curl -vk https://localhost?a=b
          curl -vk -X HEAD https://localhost
          curl -vk -X OPTIONS https://localhost
          curl -vk -H Referer:http://www.example.com -H X-Forwarded-For:127.0.0.128 https://localhost/
          curl -vk --cookie COOKIE=test_cookie https://localhost
          curl -vk https://localhost
          curl -v https://host1.internal || true
          curl -v https://host2.internal || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - logs
        run: |
          set -x
          ls -la /var/log/
          ls -la /var/log/nginx
          find /var/log/nginx -type f -exec tail -50 {} \;
          cat /var/log/gixy.log
          cat /var/log/php-fpm.log || true
          cat /var/log/php7.2-fpm.log || true
          cat /var/log/php7.4-fpm.log || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - journalctl
        run: |
          set -x
          sudo journalctl -xeu nginx -l --no-pager | tail -500
        if: ${{ always() }}
        continue-on-error: true
